car_type = ["sedan", "SUV", "crossover", "minivan", "hatchback", "sports car", "convertible", "RV", "truck", "hybrid", "electric"]

cars = [["truck", "Toyota", "Tacoma", "2", "2", "45"],
        ["truck", "Toyota", "Tundra", "4", "5", "56"],
        ["sedan", "Toyota", "Camry", "4", "5", "41"],
        ["sedan", "Toyota", "Camry-hybrid", "4", "5", "48"],
        ["hybrid", "Toyota", "Camry-hybrid", "4", "5", "48"],
        ["sedan", "Toyota", "Corolla", "4", "5", "38"],
        ["hybrid", "Toyota", "Prius-base", "2", "5", "42"],
        ["sedan", "Toyota", "Prius-base", "2", "5", "42"],
        ["hybrid", "Toyota", "Prius", "4", "5", "46"],
        ["sedan", "Toyota", "Prius", "4", "5", "46"],
        ["minivan", "Toyota", "Sienna", "4", "8", "54"],
        ["sports car", "Toyota", "Supra", "2", "2", "89"],
        ["SUV", "Toyota", "Highlander", "4", "7", "62"],
        ["crossover", "Toyota", "Venza", "4", "5", "50"],
        ["SUV", "Toyota", "Rav-4", "4", "5", "55"],
        ["hybrid", "Toyota", "Rav-4-hybrid", "4", "5", "60"],
        ["SUV", "Toyota", "Rav-4-hybrid", "4", "5", "60"],
        ["SUV", "Toyota", "4Runner", "4", "6", "65"],
        ["electric", "Toyota", "bZ4x", "4", "5", "60"],
        ["sports car", "Ford", "Mustang", "2", "4", "75"],
        ["convertible", "Ford", "Mustang Convertible", "2", "4", "75"],
        ["truck", "Ford", "F-150", "4", "6", "59"],
        ["truck", "Ford", "Ranger", "2", "4", "45"],
        ["truck", "Ford", "Maverick", "4", "5", "45"],
        ["truck", "Ford", "F-150 Lightning", "4", "6", "65"],
        ["electric", "Ford", "F-150 Lightning", "4", "6", "65"],
        ["SUV", "Ford", "Escape", "4", "5", "47"],
        ["electric", "Ford", "Mustang Mach-E", "4", "5", "74"],
        ["SUV", "Ford", "Bronco", "2", "4", "67"],
        ["SUV", "Ford", "Bronco Sport", "4", "5", "59"],
        ["SUV", "Ford", "Explorer", "4", "6", "60"],
        ["sedan", "Chevrolet", "Malibu", "4", "5", "41"],
        ["hatchback", "Chevrolet", "Spark", "4", "4", "38"],
        ["sports car", "Chevrolet", "Camaro", "2", "4", "69"],
        ["sports car", "Chevrolet", "Corvette", "2", "2", "80"],
        ["electric", "Chevrolet", "Bolt EV", "4", "4", "46"],
        ["truck", "Chevrolet", "Colorado", "2", "4", "45"],
        ["truck", "Chevrolet", "Colorado", "4", "4", "48"],
        ["truck", "Chevrolet", "Silverado", "4", "5", "61"],
        ["SUV", "Chevrolet", "Trailblazer", "4", "5", "55"],
        ["SUV", "Chevrolet", "Tahoe", "4", "7", "65"],
        ["convertible", "Chevrolet", "Camaro Convertible", "2", "4", "69"],
        ["crossover", "Chevrolaet", "Trax", "4", "5", "40"],
        ["electric", "Tesla", "Model S", "4", "5", "75"],
        ["SUV", "Honda", "CR-V", "4", "5", "50"],
        ["minivan", "Honda", "Odyssey", "4", "8", "55"],
        ["SUV", "Honda", "HR-V", "4", "6", "48"],
        ["SUV", "Honda", "Pilot", "4", "6", "50"],
        ["sedan", "Honda", "Civic", "4", "5", "41"],
        ["sedan", "Honda", "Civic-hybrid", "4", "5", "45"],
        ["hybrid", "Honda", "Civic-hybrid", "4", "5", "45"],
        ["sedan", "Honda", "Accord-hybrid", "4", "5", "48"],
        ["hybrid", "Honda", "Accord-hybrid", "4", "5", "48"],
        ["sedan", "Honda", "Accord", "4", "5", "45"],
        ["truck", "Honda", "Ridgeline", "4", "5", "55"],
        ["hatchback", "Honda", "Civic Hatchback", "4", "5", "45"],
        ["crossover", "Honda", "HR-V", "4", "5", "40"],
        ["RV", "Airstream", "Land Yacht", "3", "8", "98"],
        ["RV", "Monaco", "Dynasty 42DS", "3", "8", "100"]
]

